### ISSUE TITLE
Feature: use negative number as ago() inputs

### ISSUE THREAD

**Issue by meven** [jk-gan/aion#5]
Using u64 and negative number could be handy to express time relative to now, i.e ago().

I.e
```rust
let last_week = 7.days().ago();
assert!(last_week == -7.days());
```
But it may hurt too much readability and expressiveness, being too magic.

**Comment by jk-gan** [comment]
In my opinion, I would prefer to use `7.days().ago()` more than `-7.days()` because I find the latter is more confusing to me.
