### ISSUE TITLE
Feat: Multiple duration combination

### ISSUE THREAD

**Issue by plwai** [jk-gan/aion#6]
Support for combination like 2 weeks 3 days later. 

```rust
// First proposal
let duration = 2.weeks().and(3.days());

// Second proposal
let duration = 2.weeks(3.days());

// Third proposal
let duration = combine!(2.weeks(), 3.days())
```

**Comment by jk-gan** [comment]
Is there a use case for this? Just want to make sure so we won't make the crate too complicated.

**Comment by plwai** [comment]
Actually, I just realize it can be

```rust
let duration = 2.weeks().form_now() +3.days().from_now();
```

**Comment by jk-gan** [comment]
I suppose ur suggestion on `2.weeks().and(3.days())` will be a duration, so the equivalent implementation should be:
```rust
let duration = 2.weeks() + 3.days();
```

**Comment by jk-gan** [comment]
Closing this issue since there is a working solution on this. Thanks @plwai for the suggestions. Appreciate that.
